---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
   - name: Check hostname
     ansible.builtin.command: ansible-navigator images
     register: result

   - name: Print result
     ansible.builtin.debug:
       var: result
